pipeline {
    agent any
    stages {
        stage('print-php-version') {
            steps {
                sh 'php --version'
            }
        }
        stage('print-date') {
            steps {
                sh 'date'
            }
        }
    }
}
