pipeline {
    agent any
    stages {
        stage('print-php-version') {
            when {
                changeset "job2/Jenkinsfile"
            }
            steps {
                sh 'php --version'
            }
        }
        stage('print-hostname') {
            steps {
                sh 'hostname'
            }
        }
        stage('print-date') {
            steps {
                sh 'date'
            }
        }
    }
}
