pipeline {
    agent any
    stages {
        stage('print-ruby-version') {
            steps {
                sh 'ruby -v'
            }
        }
        stage('print-date') {
            steps {
                sh 'date'
            }
        }
    }
}
